### ISSUE TITLE
Exception reported: Client X is not in game Error

### ISSUE THREAD

**Issue by AhRoon** [Silenci0/SMAC#7] opened 2019-05-04 12:52 UTC
Hi,

I keep getting this error about Exception reported: Client X is not in game(Note: X is the number, and the number is random).
Please note that I'm using the Bots Features on the server.

Can you fix this issue or do you have any solutions about this?

**Comment by AhRoon** [comment] 2019-05-04 12:52
L 05/04/2019 - 21:47:28: [SM] Exception reported: Client 7 is not in game
L 05/04/2019 - 21:47:28: [SM] Blaming: smac_speedhack.smx
L 05/04/2019 - 21:47:28: [SM] Call stack trace:
L 05/04/2019 - 21:47:28: [SM]   [0] IsPlayerAlive
L 05/04/2019 - 21:47:28: [SM]   [1] Line 123, Y:\SourcemodProjects\_SMDevENV\addons\sourcemod\scripting\smac_speedhack.sp::OnPlayerRunCmd

**Comment by Silenci0** [comment] 2019-05-04 17:59
I think I see what the problem is and I will fix it soon. Also, what game is this for?

**Comment by AhRoon** [comment] 2019-05-05 00:20
@Silenci0 Team Fortress 2.

**Comment by Silenci0** [comment] 2019-05-07 14:27
I did not run into this issue myself, personally, on my TF2 test server, but I think I found the issue and hopefully resolved it. The error you are seeing is due to whatever client 7 is no longer being connected and/or in game during the time that the check is run. Client 7 could easily be a player or a bot, but in either case, it took an action directly before disconnecting so the check would then fail at this step.

While I have, hopefully, resolved this issue in the latest 0.8.6.4 update, I cannot guarantee that an edge case won't occur depending on the timing of the action vs. the disconnect. Unless this issue completely breaks the plugin, I think it can safely be ignored. Thanks for the report, closing issue.

**Closed by Silenci0** 2019-05-07 14:27 UTC
Labels: TF2, bug
