### ISSUE TITLE
L4D2 command blocker

### ISSUE THREAD

**Issue by lunatixxx** [Silenci0/SMAC#6] opened 2019-04-29 06:59 UTC
Commands block plugins is broken of Left 4 Dead 2, don't know about other games. I remember seeing on l4dblog a long time ago than developpers updated the game to avoid "malicious" servers blocking client commands, i guess this is what broke the plugin. You can add new commands to block but it will not do anything from what i know.

For example when my character is down i can still open or close a door with a console command who is supposed to be banned "choose_closedoor" and "choose_opendoor". I guess many other cheat commands could be abused, i did not test them all.

**Comment by Silenci0** [comment] 2019-04-29 13:15
Thank you for the report. There are several commands it should block, but perhaps L4D2 is different in that regard. Another good alternative might be this plugin here: https://forums.alliedmods.net/showthread.php?t=73828 

Its an older plugin, but its simplistic and generally works. The difference between the two is the approach in blocking commands, but generally, what the command blocker can't or won't block, this one generally does. That said, I don't know if this works in L4D2, so you'll probably need to give it a shot.

**Comment by lunatixxx** [comment] 2019-04-29 13:51
Thanks i will try it.

**Comment by lunatixxx** [comment] 2019-04-29 14:28
Oh wait, i added "choose_closedoor" by my self in smac.cfg but this time with the ban activated and it works too. But it will still be nice if the block function were working.

**Comment by Silenci0** [comment] 2019-05-04 18:02
I would not know since this is the first I've heard about this kind of bypass. I think that would require some research on how it is being done in order to determine if its possible to prevent or not.

**Comment by lunatixxx** [comment] 2019-05-25 21:21
Banning choose_closedoor and his brother is not possible by the way, or it ban people when they interact with doors. Valve has to fix it probably.

**Comment by Silenci0** [comment] 2019-07-26 06:39
Sorry for the late reply on this, but I looked into this further and the SMAC plugin already has these listed as commands it is meant to ignore in the code file itself, so it should ignore these command already, but since they are not being ignored, it might be another issue with these commands that valve needs to fix (the commands could be client-side which is why people can still use them). I have looked up these commands and the searches turn up results similar to what you are asking for with people responding with the same responses.

At this point, the only options available to potentially remedy this are as follows:

- Attempt to set these commands as an sv_cheat, which can potentially be done with this plugin here (it was linked earlier in this thread): https://forums.alliedmods.net/showthread.php?t=73828
- Create another plugin that changes how these two commands are processed on the server when sent from the client. If setting the command as an sv_cheat does not work or this command is client-side and cannot be removed or blocked via the server, it will most likely fall to this option to remedy it. This one is far more tricky/more difficult to do and there is no guarantee that it could even be done, so its the long shot when all else fails.

Ultimately, I think you are right, this is a command that Valve will need to take care of, but considering how long it has been since it was a concern, it might need to be brought up to them again with more concrete examples on how to reproduce the issues seen when using these commands. 

Thank you for the report, if you run into anymore issues, feel free to open a new issue. Closing issue.

**Closed by Silenci0** 2019-07-26 06:39 UTC
Labels: L4D2
